<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CSharpGit.Application/CSharpGit.Application.csproj" />
    <ProjectReference Include="../CSharpGit.Domain/CSharpGit.Domain.csproj" />
  </ItemGroup>
</Project>
